DATASET:
  BATCH_SIZE: 32
  RLBENCH:
    TASK_NAME: 'hoge' # PickUpCup PutKnifeOnChoppingBoard PutRubbishInBin StackWine StackBlocks TakePlateOffColoredDishRack ReachTarget PushButton CloseBox PutUmbrellaInUmbrellaStand ScoopWithSpatula
    PATH: '../dataset/RLBench-Local'
OUTPUT:
  LOG_ITER: 100
  EVAL_ITER: 5000
  MAX_ITER: 100000
  SAVE_ITER: 10000
  BASE_DIR: "../global_result"
OPTIM:
  LR: 1e-4
  SCHEDULER:
    GAMMA: 0.99
    STEP: 5000
VAE:
  NAME: "Transformer_VAE" # Transformer_VAE
  LATENT_DIM: 256
  KLD_WEIGHT: 0.01