SAMPLING:
  LIMIT_SAMPLE: 8
  LANGEVIN:
    STEP_SIZE: 0.001
    MOMENTUM : 0.
    ITERATION: 100
    DECAY_RATIO: 1.0
    DECAY_STEP: 10
  LANGEVIN_VAE:
    STEP_SIZE: 0.01
    MOMENTUM : 0.
    ITERATION: 100
    DECAY_RATIO: 1.0
    DECAY_STEP: 10
  DMO:
    LIMIT_SAMPLE: 8
    ITERATION: 5
    THRESHOLD: -1000.
